name: Build WebView APK

on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'Nama Aplikasi'
        required: true
      webUrl:
        description: 'URL Website'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # UPDATE: Mengubah v3 menjadi v4
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Data dari GAS ke Source Code
        run: |
          sed -i 's/<string name="app_name">.*<\/string>/<string name="app_name">${{ github.event.inputs.appName }}<\/string>/g' app/src/main/res/values/strings.xml
          sed -i 's|private String targetUrl = ".*";|private String targetUrl = "${{ github.event.inputs.webUrl }}";|g' app/src/main/java/com/contoh/webview/MainActivity.java

      # UPDATE: Mengubah v3 menjadi v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Berikan Izin Eksekusi pada Gradle
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      # UPDATE: Mengubah v3 menjadi v4
      - name: Upload APK Hasil Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.appName }}-APK
          path: app/build/outputs/apk/debug/app-debug.apk
