name: Generate Keystore Sementara

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Buat Keystore dan Ubah ke Base64
        run: |
          keytool -genkey -v -keystore release-key.jks -alias myalias -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Darus, O=Personal, C=ID" -storepass rahasia123 -keypass rahasia123
          base64 -w 0 release-key.jks > keystore_base64.txt

      - name: Download Hasil Base64
        uses: actions/upload-artifact@v3
        with:
          name: Hasil-Base64
          path: keystore_base64.txt
